export const QUERY_PARAMS = {
  ME: 'QUERY.ME',
  ALL_USERS: 'QUERY.ALL_USERS',
  ALL_PRODUCTS: 'QUERY.ALL_PRODUCTS',
  ALL_ORDERS: 'QUERY.ALL_ORDERS',
  PRODUCT_DETAIL: 'QUERY.PRODUCT_DETAIL',
  ORDER_DETAIL: 'QUERY.ORDER_DETAIL',
  REVENUE: 'QUERY.REVENUE',
}